[toolchain]
channel = "1.88.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
missing_signer = "HF33f3iZYeK7qz7AE1aWWGvQuxArTudNjKVseAhTYCRC"
missing_owner = "8anCcUkKVms75R4HYTnkbM6YGzAra9WTmXhNEY5RSaNw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 patterns/**/tests/*.ts"
